// Generated by CoffeeScript 1.3.3
(function() {
  var Q, bcrypt, crypto, db, exports, mongo, monk;

  bcrypt = require('bcryptjs');

  crypto = require('crypto');

  Q = require('q');

  mongo = require('mongodb');

  monk = require('monk');

  db = monk('localhost:27017/cyc');

  exports = module.exports = {};

  exports.signin = function(username, passhash) {
    var stored_hash, token, users;
    users = db.get('users');
    stored_hash = users.find({
      username: username
    }, {}, function(e, docs) {
      return docs.passhash;
    });
    if (bcrypt.compareSync(stored_hash, passhash)) {
      token = crypto.randomBytes(16).toString('hex');
      users.update({
        username: username
      }, {
        $set: {
          loggedin: true,
          token: token
        }
      });
      return token;
    } else {
      users.update({
        username: username
      }, {
        $set: {
          loggedin: false
        }
      });
      return false;
    }
  };

  exports.signout = function(username, token) {
    var loggedin, stored_token, users;
    users = db.get('users');
    stored_token = '';
    loggedin = false;
    users.find({
      username: username
    }, {}, function(e, docs) {
      stored_token = docs.token;
      loggedin = docs.loggedin;
    });
    if (loggedin && stored_token === token) {
      users.update({
        username: username
      }, {
        $set: {
          loggedin: false
        }
      });
      return true;
    } else {
      console.log('Attempted illegal logout from {username}');
      return false;
    }
  };

}).call(this);
